services:
  - type: web
    name: fastapi-app
    runtime: docker
    repo: https://github.com/RRRus3575/goit-pythonweb-hw-012
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: REDIS_URL
        sync: false
    region: oregon
